### ISSUE TITLE
Permissions Error when starting the the nuxt container

### ISSUE THREAD

**Issue by chmey** [chiefonboarding/ChiefOnboarding#16] opened 2020-10-23 19:32 UTC
# Steps to reproduce:
1. Clone main branch
2. rename `back/back/.env.example` to ` back/back/.env` 
3. build the images
4. run `docker-compose up` 

# Expected outcome
Containers start normally

# Actual outcome
nuxt container crashes because of a permissions error

```
Attaching to chiefonboarding_nuxt_1
nuxt_1         | 
nuxt_1         | > ChiefOnboarding@1.0.0 postinstall
nuxt_1         | > npm run build && node ./postinstall.js
nuxt_1         | 
nuxt_1         | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
nuxt_1         |   errno: -13,
nuxt_1         |   code: 'EACCES',
nuxt_1         |   syscall: 'scandir',
nuxt_1         |   path: '/root/.npm/_logs'
nuxt_1         | }
nuxt_1         | 
nuxt_1         | > ChiefOnboarding@1.0.0 build
nuxt_1         | > nuxt build
nuxt_1         | 
nuxt_1         | sh: 1: nuxt: not found
nuxt_1         | npm ERR! code 127
nuxt_1         | npm ERR! path /var/www/app
nuxt_1         | npm ERR! command failed
nuxt_1         | npm ERR! command sh -c nuxt build
nuxt_1         | npm notice 
nuxt_1         | npm notice New patch version of npm available! 7.0.3 -> 7.0.5
nuxt_1         | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.5>
nuxt_1         | npm notice Run `npm install -g npm@7.0.5` to update!
nuxt_1         | npm notice 
nuxt_1         | npm ERR! code 127
nuxt_1         | npm ERR! path /var/www/app
nuxt_1         | npm ERR! command failed
nuxt_1         | npm ERR! command sh -c npm run build && node ./postinstall.js
nuxt_1         | 
nuxt_1         | npm ERR! A complete log of this run can be found in:
nuxt_1         | npm ERR!     /root/.npm/_logs/2020-10-23T19_28_18_252Z-debug.log
```

Possibly `node` image runs a the node user or something while the Dockerfile uses the root user to build.

**Comment by chmey** [comment] 2020-10-23 19:33
Should I look into this?

**Comment by GDay** [comment] 2020-10-23 19:41
That's weird. Feel free, if you want to. 

It might be easily fixed by adding `--unsafe-perm=true --allow-root` to this line:  https://github.com/chiefonboarding/ChiefOnboarding/blob/master/docker-compose.yml#L63 (so, it would be: `npm install --unsafe-perm=true --allow-root && npm run dev`).

I see if I can get the same error on my machine.

**Comment by GDay** [comment] 2020-10-23 19:47
Oh wait... why is it building the source? That's not right - it should only do that when running the `server_script.sh`.

```
command sh -c npm run build && node ./postinstall.js
```
That's not okay. The normal `docker-compose.yml` file shows that it should do `command: bash -c "npm install && npm run dev"`

**Comment by chmey** [comment] 2020-10-23 20:02
Must be because of the `./front` mount: https://github.com/chiefonboarding/ChiefOnboarding/blob/1755c85f1a8edd723bfb933fcbd6a8c79f7fbde6/docker-compose.yml#L62

**Comment by GDay** [comment] 2020-10-23 20:03
I think I know why it does that. If you uncomment this line: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/front/package.json#L15 (and remove the comma on the line before), then it will probably work fine. I am still trying to reproduce it, somehow it works for me...

**Comment by GDay** [comment] 2020-10-23 20:46
I have still not been able to reproduce this issue, but I have just pushed a (potential) fix for this - if you download the repo again (or just change the two files that I changed), then it should not build the source anymore.

Apologies for the inconvenience! Let me know if it works now.

**Closed** 2020-10-26 15:44 UTC

**Comment by mangatinanda** [comment] 2020-12-18 07:52
Hey, I just pulled the repo and trying to setup in my local ubuntu 20.4 and facing similar error when building nuxt container. Here is the error:
`nuxt_1         | 
nuxt_1         | > ChiefOnboarding@1.0.0 dev
nuxt_1         | > nuxt
nuxt_1         | 
nuxt_1         | sh: 1: nuxt: not found
nuxt_1         | npm ERR! code 127
nuxt_1         | npm ERR! path /var/www/app
nuxt_1         | npm ERR! command failed
nuxt_1         | npm ERR! command sh -c nuxt
nuxt_1         | 
nuxt_1         | npm ERR! A complete log of this run can be found in:
nuxt_1         | npm ERR!     /root/.npm/_logs/2020-12-18T07_34_54_711Z-debug.log
chefonboard_nuxt_1 exited with code 127
`

**Comment by mangatinanda** [comment] 2020-12-18 10:53
I changed [this line](https://github.com/chiefonboarding/ChiefOnboarding/blob/1755c85f1a8edd723bfb933fcbd6a8c79f7fbde6/docker-compose.yml#L63) to `npm install && npm install -g nuxt && npm run dev` and it worked. @GDay

**Comment by GDay** [comment] 2020-12-18 13:22
Thanks a lot @mangatinanda. Just fixed that!
