### ISSUE TITLE
Provisioning to Heroku fails

### ISSUE THREAD

**Issue by githubber** [chiefonboarding/ChiefOnboarding#74] opened 2021-05-27 08:55 UTC
Looks like a great app. I'm trying to install on Heroku, following the instructions at https://docs.chiefonboarding.com/Deployment.html#deploying, but it fails very quickly, with the two messages below appearing almost immediately after pressing `Deploy app`.

`Create app
App creation failed. Please ensure you have valid values in the above form fields.

Configure environment
There was an issue setting up your app environment.

an unexpected error caused the job to fail`

I thought I would test different variables, so I changed the `SSL_REDIRECT` to `false` (and changed the Base url to http), and then the app passed the `Create app` section, and spent several minutes on `Configure environment`. It then continued on to `Build app`, with all the logs scrolling by. It took less than a minute for `run scripts & scale dynos` to finish, and then the green `Deploy to Heroku` appeared, along with the message, `Your app was successfully deployed.` Hooray!

However, the `View` link included the https, not http. And when I follow that link, there is a white rectangular box with a spinning yellow loader. Whether I leave it as https or http, the yellow loader just spins and spins.

So I've gone into the App Settings (under Manage app in the Heroku Dashboard), and have tried changing the config variables back to the original suggestions - using https, and TRUE for directing all traffic to https, then restarted the dyno.

I noticed there was more to the setup, so I did all that. But the last hiccup was that running `python manage.py loaddata welcome_message.json all.json` in the Console returned an error that there was no `organizatio` (yes, a missing m). 

Anyway, after all this the app was accessible, and a login window replaced the spinning yellow loader. I was able to login, and adjust some of the config variables. 

I suppose the main problem was the app failure right at the beginning. I don't how much of a priority the Heroku option is for you, but the same issue might happen for others self-hosting elsewhere. So, you prob wanna see what's causing this failure.

**Comment by GDay** [comment] 2021-05-27 12:43
Thanks for letting me know! I was actually aware of these issues and there is a PR that resolves everything. I just haven't gotten to fully test and merge it yet. I am sorry about the inconvenience. 

The error during installation is caused by using `true` instead of `True` for the `SSL_REDIRECT` variable. ([Fixed here](https://github.com/chiefonboarding/ChiefOnboarding/commit/b155634a0af5388839325aa6b3041f6ca2f50fb4))

The issue with the fixture is fixed [here](https://github.com/chiefonboarding/ChiefOnboarding/pull/70/files).

I will leave this issue open and will make it more obvious that additional tasks are necessary after deploying to Heroku. 

Thanks for trying it out and thanks again for reporting this!

**Comment by GDay** [comment] 2021-06-09 19:10
These issues should be fixed now. I have just released the new version. It will now also automatically create an organization, create the first user account (which you can specify yourself) and import all demo data.

I will close this issue now, but if you are still having trouble, then feel free to comment/create a new issue.

**Closed by GDay** 2021-06-09 19:10 UTC
