### ISSUE TITLE
Preboarding form not recording all responses

### ISSUE THREAD

**Issue by xboxhaxorz** [chiefonboarding/ChiefOnboarding#466] opened 2024-04-30 00:42 UTC
I made a screengrab of the issue https://vento.so/view/0cfd9fb3-ee9c-4bfb-b476-d3bb846ed0c1?utm_medium=share

But basically there are 2 pages of ?s and the 2nd page doesnt get recorded in the employees profile

**Comment by GDay** [comment] 2024-04-30 02:28
Thanks a lot for the video.
This is really strange. I cannot seem to reproduce the issue. It always saves it for me. 

![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/1939656/b2410398-d97a-4f26-af01-0803b49014a8)

Could you try to recreate that preboarding page you made (the template)?

**Comment by xboxhaxorz** [comment] 2024-05-01 01:13
Your welcome

I created it from scratch and this was how it worked https://vento.so/view/70cbf32d-a448-4b7d-b56a-f8c880c0adbf?utm_medium=share

It did show all form responses but it had 2 submit buttons

**Comment by GDay** [comment] 2024-05-02 02:22
Thanks. 

I have just pushed an update that will hide the preboarding button when there are no preboarding items assigned to the user.

The two buttons was intended as you could easily have multiple forms and a user wouldn't need to submit both at the same time. Looks like there is a bug that will mess up the second form when there are two. Will fix this soon.

I was also able to replicate that issue with the form not saving. That's an issue with the default form that's created. If you create new ones, then it should work fine (as long as it's one form).

Will fix both issues in the next few days.

**Comment by xboxhaxorz** [comment] 2024-05-03 03:08
Your welcome

So when i used the demo form previously there were 2 separate forms/ pages each with their own button as they each had their own page

The form that i made in the above screengrab was a single form just with some plain text between them, so it should be a single submit button per page correct?

Thanks ill get the new patch and test

**Comment by GDay** [comment] 2024-05-03 03:14
No, any break of the form by another type of content will break the form in two. So, even some text in between will make it two forms.

Op vr 3 mei , xboxhaxorz ***@***.***(mailto:Op vr 3 mei  , xboxhaxorz <<a href=)> schreef:

**Closed** 2024-05-12 01:37 UTC

**Comment by GDay** [comment] 2024-05-12 01:42
This has been fixed in the latest release. The default form won't work for already installed instances, you will need to create a new form. It will now take the whole page as one form to submit.
