### ISSUE TITLE
404 on new hire login after change of password

### ISSUE THREAD

**Issue by clement8888** [chiefonboarding/ChiefOnboarding#127] opened 2022-03-12 05:25 UTC
hello, i was trying out the chiefonboarding on render and when i tried to change the password for the new hire, it would log the new hire in but would give a 404 error.  I have tried to change the email of the new hire and resend a invitation to login again and the same would occur.  Even erasing the new hire and creating a new new hire record would give the 404 upon login.

**Comment by clement8888** [comment] 2022-03-12 08:13
just a update.  i have redeployed chiefonboarding and tested it again. This time i managed to recreate the above 404 situation but it is after I sent a preboarding email to the new hire.  the new hire's start date has already passed (set as 1 March 2022) when i sent the preboarding email. Thereafter, logging into the new hire's account will give 404.

**Comment by GDay** [comment] 2022-03-12 16:33
I am working on a new version which will be released soon, but from what I remember, that is intended behavior. When they have past the start day, then preboarding isn't useful anymore. Preboarding is only used for before the new hire starts.

Once the new hire has started you can send them a login email with credentials (or let them login via Google SSO). You can send the email when clicking on the new hire -> the three dots in the top right -> Send login email.

Hope that helps.

**Closed** 2022-07-15 23:55 UTC
